### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by marcelmatula** [rokusjar/KotlinSkoleni#10]
- There's no synchronized keyword in Kotlin - use @Synchronized nebo top level function synchronized { }
Note that synchronized is a function in Kotlin which returns a value. This makes it more powerful than Java's synchronized keyword. 

- There's no volatile keyword in Kotlin - use @Volatile
- Kotlin's Any, which is analogous to Java's Object, doesn't have wait(), notify() and notifyAll() methods

- how to create thread - thread { .. }.start()

**Locking**

kotlin ma extention withLock na Lock tride
```
public inline fun <T> Lock.withLock(action: () -> T): T {
    lock()
    try {
        return action()
    } finally {
        unlock()
    }
}
```

The extension withLock works on Lock instances like ReentrentLock, whereas synchronized may be used with any object.
```kotlin
    val lock = ReentrantLock()
    fun syncWithLockTest(): Int = lock.withLock { 123 }

    val anyLock = Any()
    fun syncWithArbitraryObjTest(): Int = synchronized(anyLock) { 123 }
```

Navic Kotlin ma extensions
ReentrantReadWriteLock.read

```
    val rwLock = ReentrantReadWriteLock()
    rwLock.read { 
        // whatever code under Read lock
    }
    rwLock.write { 
        // whatever code under Write lock
    }
```

ReentrantReadWriteLock.write

Link:
https://blog.egorand.me/concurrency-primitives-in-kotlin/

Task udelam ja a bude to napsat SleepSort v Kotlin-u

**Comment by rokusjar** [comment]
@marcelmatula přidal jsem slajdy na Concurrency. Koukni na to prosím, jestli to takhle stačí. Držel jsem se pouze toho co jsi napsal do tasku.

**Comment by marcelmatula** [comment]
dik - za me ok - upravil jsem jenom page 4 a zamenil 123  s ...
