### ISSUE TITLE
pridat sekci na konverze a casting

### ISSUE THREAD

**Issue by marcelmatula** [rokusjar/KotlinSkoleni#2]
Bezne pri prechodu z java do kotlinu lidem dela problem
jak udelal konverzi int na long nebo precastovat object typu Person na object Teacher,
nebo jak udelat zo set-u udelat list

mohl bys prosim te pridat 1-2 slides + jednoduche TODO priklady taky na github?
Neco uz mas na slide-u 9 a 28 a chtelo by to zduraznit.

ukazky/priklady casting a konverze
-     2L.toInt() // long to int
    2.23.toBigDecimal() // float to big decimal
    30.toLong() // int to long
    1.toFloat()
    2.toDouble()
- setOf().toList(), 
- listof().toMutableList()
- smart cast - pozor na var ( nefunguje protoze reference muze byt zmenena)
```
val a: Any = "aaa"
if ( a is String ) { println(a.isEmpty()) } // v jave instanceOf -- tohle je uz na slide c. 9
// tohle bych dal jako testovaci priklad do githubu
val b = when (a) {
   is String -> a
   else -> a.toString()
}
```
```
val a:Any = "xxxx"
val b = a as String
```

tohle uz mas na slide 9
"Safe" (nullable) cast operator
To avoid an exception being thrown, one can use a safe cast operator as? that returns null on failure:
`val x: String? = y as? String`

**Comment by rokusjar** [comment]
Přidal jsem příklad a do prezentace jsem doplnil slajdy. Vznikla sekce Casting a konverze.

**Comment by marcelmatula** [comment]
mohl by jeste pridat na slide k smart cast-u 
jako otazku jestli se nasledujici kod z kompiluje:
fun printLength(name: String?) {
    if (name == null) return
    println(name.length)
}

**Comment by marcelmatula** [comment]
mohl by jeste pridat na slide k smart cast-u
jako otazku jestli se nasledujici kod z kompiluje:
```
fun printLength(name: String?) {
  if (name == null) return
    println(name.length)
}
```

**Comment by rokusjar** [comment]
@marcelmatula přidáno
