### ISSUE TITLE
Ranges + In operator

### ISSUE THREAD

**Issue by marcelmatula** [rokusjar/KotlinSkoleni#3]
na slide-u 6 :String and Ranges mas par prikladu na range ale
casto pri prechodu na kotlin lide nepouzivaji ranges takze by to chcelo dat simple todo task do githubu + rozsirit ten  slide c. 6

jako zadani bych dal uplne simple task
// uprav nasledujici kotlin code aby pouzival ranges and 'in' operator v podmince
```
if (x >=0 && x <=10) {
   println("$x is in range")
}
takze by to meli prespat na
if (x in 0..10) { }

```
do slidu pridat - !in, until, downTo, step and taky forEach equivalent
par prikladu - nemusit tam samozrejme davat vsetchno
for (i in 1..4) print(i)
nebo
(0..4).forEach { }

for (i in 4 downTo 1) print(i)
(4 downTo 1).forEach{ println(it)}

for (i in 1 until 10) // 10 is excluded
(0 until 10).forEach{ println(it)}

if ('c' in 'a'..'z')
if ('c' !in 'a'..'z') not in

in je infix operator s vyuzitim contains()
pouziti v list, map, set, array
val list = listOf(3,4,6)
if (x in list) ...

step 
for (i in 1..4 step 2) print(i)
for (i in 4 downTo 1 step 2) print(i)

**Comment by rokusjar** [comment]
Doplnil jsem příklad a jeho řešení. Do prezentace jsem přidal sekci Ranges, kde jsem na jednom slajdu shrnul příklady.
