### ISSUE TITLE
Advanced - java interop

### ISSUE THREAD

**Issue by marcelmatula** [rokusjar/KotlinSkoleni#5]
pripravit slides for sekci "Java interop" + TODO priklady 

const a @JvmField 
@JvmStatic, 
@JvmOverloads

@file:JvmName a @file:JvmMultifileClass 

Lambda arguments - volani Kotlin lambdy z java

podrobnosti najdes

https://developer.android.com/kotlin/interop

**Comment by rokusjar** [comment]
@marcelmatula Ohledně volání Kotlin lambdy z Javy si měl na mysli jen ten problém s návratovou hodnotou typu Unit, nebo ještě něco jiného?

**Comment by marcelmatula** [comment]
nic kontretniho jsem nemel na mysli - jen to proste ukazat jak se to provola a kdyz tam je problem tak ho popsat

**Comment by marcelmatula** [comment]
jeste prosim te volani z java kotlin object singletonu
object Utils {
....
fun foo() { ...}
}

v jave 
Utils.INSTANCE.foo()

**Comment by rokusjar** [comment]
@marcelmatula @VitekKlugi 

Ahoj,

pushnul jsem cvičení na Java Kotlin interoperability. Koukněte na to prosím, jestli je to podle vás OK.

Díky. Míra

**Comment by marcelmatula** [comment]
Ahoj,

za me ok - dik

Marcel
