### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by marcelmatula** [rokusjar/KotlinSkoleni#6]
slides + github todo tasky

- any, none, all
- first, last, filter, find, map, flatMap, partition, sortBy, count, zip. distinct, groupBy, associateBy (only if key is unique otherwise use groupBy)

Why asSequancial() - tady by to chtelo priklad+todo - ten pripravim ja

list,map,set
- plus, minus operator
- pozor val list = ArrayList<String> (nebo listof(1,2,3))  je readonly List (add nenajdes v IDEA napovede)
- moznost toMutableList() nebo plus, minus methods
```kotlin
val list = listOf(1,2,3)
val newList = list + 2 // list is not changed - new copy is created and added 2

val mutableList = mutableListOf(1,2,3)
mutableLIst += 4 // no copy - 4 is added directly to mutabel List
```

How to init list,set array
```kotlin
    println(List(5) { (0..10).random() })
    println(List(5) { it })
    println(Array(5) { it })
```
Stahni si screenshorty z coursera skoleni a pouzito/uprav podle protreby
https://www.dropbox.com/s/yqjt7yvts39lqba/collections.zip?dl=1

Zduraznit
- Be carefull 
- consider using asSequancial for large collections or if chain call is too long
(note that asSequancial is not inline function)
- don't use "it" if it has different types in neighbouring lines
- prefer explicit paramter names if it might be confusing otherwise
- learn library as much as possible

**Comment by marcelmatula** [comment]
dalsi trochu zlozitejsi TODO task:
napis kod na generovani 16 mistniho klice - povolene ascii znaky 0 (nula) az male 'z'.

pouzi range, extension function random()

reseni:
```kotlin
val key = (1..16).map { ('0'..'z').random() }.joinToString(separator = "")
```

**Comment by marcelmatula** [comment]
ahoj, tady je ten priklad na asSequence
```kotlin
    fun heavyCalculation(number: Int): Int {
        TimeUnit.SECONDS.sleep(1)
        return number * number
    }

    val time = measureTimeMillis {
        val result = (1..10)
                //.asSequence()
                .mapNotNull { heavyCalculation(it) }
                .take(2)
                //.toList()
        println(result)
    }
    println("Calculation took $time ms")
```
1) prvy run bude trvat kolem 10 sec
2) kdyz se to prevede na asSequence (odkomentaova asSequence() a .toList()
tak to zabere jenom 2 sec

je tam treba zduraznit ze kdyz delame chain of call (fiter, map, flatMap, etc) vzdy pri kazdem
kroku se vytvari nova kolekce - co vyzaduje vic pameti a muze taky hodne spomalit kod jestli se tam
dela nakladna operace ale na konci se to profiltruje a pouzije jen cast vysledku

**Comment by VitekKlugi** [comment]
Super díky zapracuji ;-)

**Comment by VitekKlugi** [comment]
Za mě je první verze finální, prosím o připomínky. Díky

**Comment by marcelmatula** [comment]
Ahoj, jeste jsem nevidel zapracovani prikladu na asSequence()
podle me je to dulezite pochopit ze to neni jenom o RAM-ke ale takze o performace a efektivnejsem zpracovani 

fun heavyCalculation(number: Int): Int {
        TimeUnit.SECONDS.sleep(1)
        return number * number
    }

    val time = measureTimeMillis {
        val result = (1..10)
                //.asSequence()
                .mapNotNull { heavyCalculation(it) }
                .take(2)
                //.toList()
        println(result)
    }
    println("Calculation took $time ms")

**Comment by VitekKlugi** [comment]
Ahoj, je to v souboru [sequence.kt](https://github.com/rokusjar/KotlinSkoleni/blob/advanced-collections-solution/src/main/kotlin/advanced/collections/sequence.kt) ten soubor cos mi tam připravil jsem zapomněl smazat, udělám.

**Comment by marcelmatula** [comment]
super dik

**Comment by VitekKlugi** [comment]
Za mě jsou příklady finalizované, pokud nemáte připomínky, přenesl bych zadání do masteru a zavřel, OK?

**Comment by marcelmatula** [comment]
za me ok - doplnil jsem reseni pro TODO 13 iterable.kt (sumByDouble, map{}.sum() )
muzes to prenes do master branch
Dik

**Comment by rokusjar** [comment]
Za mě taky ok. Míra

st 20. 2. 2019 v 9:31 odesílatel Marcel Matula <notifications@github.com>
napsal:

**Comment by VitekKlugi** [comment]
Ok, přenesl jsem instrukce do masteru, zavírám.
