### ISSUE TITLE
Advanced - Helpful extensions

### ISSUE THREAD

**Issue by marcelmatula** [rokusjar/KotlinSkoleni#8]
Ja zacatku bych uvedl ze Kotlin casto prekvapi - hledas jak neco udelat napr. nad String-em a pak najdes casto ze kotlin na to uz ma standart ext. funkci ktera to dela - to potesi :)

### String extentions
not need StringUtils anymore - kotlin String ext (je jich samozrejme vic)
```kotlin
    "".isEmpty()
    "".isNotEmpty()
    "".isBlank()
    "".isNullOrEmpty()
    "".isNullOrBlank()
    "".lines()
    "".orEmpty()        // taky mozno pomoci elvis  s?:""
    "21".padStart(3, '0')
    "".padEnd(9, '0')
    "".ifEmpty {  "whatever default" }
    "".ifBlank { "whatever default" }
```
### File / IO 
io streams - use { } for all Closeable 

```kotlin
File("my.txt").inputStream().use {
     it.read()
     ...
}
```
extension on File class
```
File.inputStream()
File.outputStream()
File.reader()
File.bufferedReader()

File.writer()
File.bufferedWriter()
File.printWriter()

File.forEachLine(...)
File.readLines(...)
File.forEachBlock(...)

File.readBytes()
File.writeBytes()
File.appendBytes()

File.readText()
File.writeText()
File.appendText()

File.copyRecursively()
File.copyTo()
File.deleteRecursively()

File.walk()
File.walkBottomUp()
File.walkTopDown()

```

### Ruzne

measureNanoTime, measureTimeMillis

```kotlin
val tookTimeInMs = measureTimeMillis {
    heavyCalculation()
} 
println("heavyCalculation took $tookTimeInMs ms")
```

### priklady + TODO tasky

**Comment by VitekKlugi** [comment]
Za mě jsou příklady finalizované, pokud nemáte připomínky, přenesl bych zadání do masteru a zavřel, OK?

**Comment by marcelmatula** [comment]
mohl bys prosim te do slide prihodit priklad na use {} a taky measureTimeMillis {}
kdyz to clovek vidi jako priklad lepe si to associuje kde to tak pouzit 
Dik

**Comment by marcelmatula** [comment]
a jeste prosim na File 
delete() je Java metoda ne extension
dej tam misto toho deleteRecursively()

Dik

**Comment by VitekKlugi** [comment]
Ahoj, díky za připomínky, zapracoval jsem. Je to takto OK?

**Comment by marcelmatula** [comment]
Ahoj, diky - je to super

**Comment by VitekKlugi** [comment]
Ok, díky. Zadání přeneseno do masteru.
