### ISSUE TITLE
Exceptions - only slides

### ISSUE THREAD

**Issue by marcelmatula** [rokusjar/KotlinSkoleni#9]
- syntax
- muze se pouzit jako expression - ukazat priklad na slide
- vsechy exception jsou unchecked v Kotlinu na rozdil od Java
- @Throw anotace pro volani z Java
- pripomenout ze throw IIlegalStateExcetion  je typu Nothing (melo by se to uz probrat v kapitole Types)

odkazy:
https://kotlinlang.org/docs/reference/exceptions.html ( tam je Nothing)
https://code.tutsplus.com/tutorials/kotlin-from-scratch-exception-handling--cms-29820

Dik

**Comment by rokusjar** [comment]
Slajdy jsem pushunl. @marcelmatula Prosím o kontrolu.

**Comment by marcelmatula** [comment]
jeste do poznamek na prvni slide bych hodil

The main difference between Kotlin and Java exception mechanisms is that all exceptions are unchecked in Kotlin. In other words, they are not explicitly declared in the function signatures, as they are in Java. 

**throws** isn't even a keyword in Kotlin

jinak za me ok - dik

**Comment by rokusjar** [comment]
Doplnil jsem poznámku.
